In [3]:
import numpy as np
import torch

In [9]:
list_mat = [[1, 2], [3, 4]]
list_mat

[[1, 2], [3, 4]]

In [10]:
tensor1 = torch.tensor(list_mat)
tensor1

tensor([[1, 2],
        [3, 4]])

In [11]:
np_arr = np.array(list_mat)
tensor2 = torch.tensor(np_arr)
tensor2

tensor([[1, 2],
        [3, 4]])

In [12]:
# 랜덤한 텐서 생성
rand_tensor = torch.rand(2, 3)
rand_tensor

tensor([[0.1900, 0.5710, 0.7286],
        [0.8471, 0.1037, 0.0337]])

In [13]:
ones_tensor = torch.ones(3, 2)
ones_tensor

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [14]:
zeros_tensor = torch.zeros(2, 2)
zeros_tensor

tensor([[0., 0.],
        [0., 0.]])

In [15]:
# shape 속성
rand_tensor.shape

torch.Size([2, 3])

In [ ]:
# 타입 확인
rand_tensor.dtype

torch.float32

In [17]:
ones_tensor.dtype

torch.float32

In [ ]:
# CPU에 올라가 있음
rand_tensor.device

device(type='cpu')

In [19]:
onse_tensor2 = torch.ones_like(rand_tensor)
onse_tensor2

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# 데이터 형이 맞지 않아 생성 불가
rand_tensor2 = torch.rand_like(tensor1)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

In [21]:
rand_tensor2 = torch.rand_like(tensor1, dtype=torch.float)
rand_tensor2

tensor([[0.3849, 0.9853],
        [0.9800, 0.5637]])

In [22]:
tensor = torch.rand(2, 3)
tensor.device

device(type='cpu')

In [32]:
if torch.cuda.is_available():
    device = "cuda:0"
else:
    device = "cpu"

In [26]:
tensor = tensor.to(device)
tensor

tensor([[0.5065, 0.8860, 0.4331],
        [0.9238, 0.5391, 0.6059]])

In [33]:
tensor2 = torch.rand(3, 2)

In [ ]:
# cuda로 보내기
tensor2.cuda()

AssertionError: Torch not compiled with CUDA enabled

# 인덱싱/슬라이싱


In [4]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [5]:
tensor[0]

tensor([1, 2, 3])

In [6]:
tensor[0, :]

tensor([1, 2, 3])

In [7]:
tensor[:, 0]

tensor([1, 4])

In [8]:
tensor[:, -1]

tensor([3, 6])

In [ ]:
# 앞에 있는 모든 차원은 모두 적용, 마지막만 -1
tensor[..., -1]

tensor([3, 6])

In [10]:
tensor2 = torch.rand(2, 3, 4, 5)
tensor2[..., -1]

tensor([[[0.8320, 0.8433, 0.2785, 0.8249],
         [0.4379, 0.4554, 0.1043, 0.7052],
         [0.6262, 0.1536, 0.6258, 0.3632]],

        [[0.7150, 0.7310, 0.1454, 0.0087],
         [0.8888, 0.0041, 0.5719, 0.4649],
         [0.0337, 0.9775, 0.4870, 0.5902]]])

In [11]:
tensor2[..., -1].shape

torch.Size([2, 3, 4])

In [12]:
tensor.sum()

tensor(21)

In [13]:
agg = tensor.sum()
agg

tensor(21)

In [14]:
agg_item = agg.item()
type(agg_item)

int

In [16]:
tensor[0, 0]

tensor(1)

In [17]:
tensor[0, 0].item()

1

In [18]:
t1 = torch.ones(2, 3)
t2 = t1 * 2
t2

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [19]:
t1

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [20]:
t1 + t2

tensor([[3., 3., 3.],
        [3., 3., 3.]])

In [21]:
t1.add(t2)

tensor([[3., 3., 3.],
        [3., 3., 3.]])

In [22]:
t3 = t1.add(t2)
t3

tensor([[3., 3., 3.],
        [3., 3., 3.]])

In [ ]:
# _가 붙으면 원본이 바뀜
t1.add_(t2)
t1

tensor([[3., 3., 3.],
        [3., 3., 3.]])

In [24]:
t1 = torch.ones(2, 3)
t2 = t1 * 2
t1 * t2

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [25]:
t1.mul(t2)

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [26]:
t1.mul_(t2)

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [27]:
t1 = torch.ones(2, 3) * 2
t1

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [28]:
t2 = torch.ones(2, 3) * 3
t2

tensor([[3., 3., 3.],
        [3., 3., 3.]])

In [29]:
# 2x3 @ 3x2 -> 2x2 (행렬곱)
t1 @ t2.T

tensor([[18., 18.],
        [18., 18.]])

In [30]:
t1.T @ t2

tensor([[12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.]])

In [31]:
t1.matmul(t2.T)

tensor([[18., 18.],
        [18., 18.]])

In [33]:
t3 = torch.matmul(t1, t2.T)
t3

tensor([[18., 18.],
        [18., 18.]])

In [34]:
t1 = torch.rand(2, 3)
t1

tensor([[0.3996, 0.4149, 0.4359],
        [0.8450, 0.6992, 0.1661]])

In [ ]:
# t1의 각 원소에 exp 함수를 적용
t1.exp()

tensor([[1.4913, 1.5143, 1.5464],
        [2.3281, 2.0121, 1.1807]])

In [36]:
torch.exp(t1)

tensor([[1.4913, 1.5143, 1.5464],
        [2.3281, 2.0121, 1.1807]])

In [ ]:
# t1의 각 원소에 log 함수를 적용
t1.log()

tensor([[-0.9172, -0.8796, -0.8303],
        [-0.1684, -0.3578, -1.7952]])

In [38]:
torch.log(t1)

tensor([[-0.9172, -0.8796, -0.8303],
        [-0.1684, -0.3578, -1.7952]])

In [39]:
t1.sum()

tensor(2.9608)

In [40]:
t1.mean()

tensor(0.4935)

In [41]:
t1.std()

tensor(0.2414)

In [42]:
t1.max()

tensor(0.8450)

In [43]:
t1.min()

tensor(0.1661)

# tensor의 결합


In [44]:
t1 = torch.ones(2, 2)
t2 = torch.ones(2, 2) * 2
t3 = torch.ones(2, 2) * 3

# tensor의 결합
torch.cat([t1, t2, t3], dim=1)

tensor([[1., 1., 2., 2., 3., 3.],
        [1., 1., 2., 2., 3., 3.]])

In [45]:
torch.cat([t1, t2, t3], dim=0)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [46]:
t1 = torch.arange(0, 12)
t1

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [47]:
t2 = t1.reshape(3, 4)
t2

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [48]:
t1.reshape(3, 5)

RuntimeError: shape '[3, 5]' is invalid for input of size 12

In [49]:
t3 = t1.reshape(2, -1)
t3

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [51]:
t4 = t1.reshape(2, 2, -1)
t4

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

In [52]:
t4.shape

torch.Size([2, 2, 3])

In [53]:
t2

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [55]:
torch.flatten(t2)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [57]:
torch.flatten(t4, start_dim=1)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [ ]:
# 1번 Dim 0, 2번 Dim 1
torch.permute(t2, dims=(1, 0))

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

In [59]:
t2

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [60]:
torch.where(t2 % 2 == 0)

(tensor([0, 0, 1, 1, 2, 2]), tensor([0, 2, 0, 2, 0, 2]))

In [64]:
t2[torch.where(t2 % 2 == 0)] = 0
t2

tensor([[ 0,  1,  0,  3],
        [ 0,  5,  0,  7],
        [ 0,  9,  0, 11]])

In [65]:
torch.randperm(12)

tensor([ 8, 11,  5, 10,  7,  9,  1,  4,  2,  6,  0,  3])

In [66]:
t1 = torch.rand(1, 1, 1, 3)
t1

tensor([[[[0.6675, 0.5892, 0.7649]]]])

In [67]:
t1.shape

torch.Size([1, 1, 1, 3])

In [69]:
t2 = t1.squeeze(dim=0)
t2.shape

torch.Size([1, 1, 3])

In [70]:
t3 = t1.squeeze(dim=[0, 1, 2])
t3.shape

torch.Size([3])

In [71]:
t1 = torch.rand(3)
t2 = t1.unsqueeze(dim=0)
t2.shape

torch.Size([1, 3])

In [72]:
t3 = t1.unsqueeze(dim=1)
t3.shape

torch.Size([3, 1])

## torch <=> numpy


In [76]:
t1 = torch.ones(2, 3)
n1 = t1.numpy()
type(n1)

numpy.ndarray

In [77]:
t1.add_(1)

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [ ]:
# 얕은 복사
n1

array([[2., 2., 2.],
       [2., 2., 2.]], dtype=float32)

In [79]:
n2 = np.ones(4)
t2 = torch.from_numpy(n2)
t2

tensor([1., 1., 1., 1.], dtype=torch.float64)

In [80]:
t3 = torch.tensor(n2)
t2.add_(1)

tensor([2., 2., 2., 2.], dtype=torch.float64)

In [81]:
n2

array([2., 2., 2., 2.])

In [ ]:
# 깊은 복사
t3

tensor([1., 1., 1., 1.], dtype=torch.float64)